### ISSUE TITLE
Question about gpu

### ISSUE THREAD

**Issue by nemo0526** [hbchen121/AICITY2022_Track2_SSM#1]
Hello, may I ask that what GPUs you used for training?

**Comment by hbchen121** [comment]
2080Ti is enough. Maybe 1080Ti is enough too.

**Comment by ZhaoChuyang** [comment]
We use 4 * 2080Ti for most of our experiments. We also tried V100, but the performace is near.

**Comment by nemo0526** [comment]
Ok, thank you!Then how long you're training takes?

**Comment by ZhaoChuyang** [comment]
Hi @nemo0526, it takes no more than 1 day on 4*2080Ti, maybe half a day is enough too because the loss does not decease explicitly after 20 epochs.

**Comment by nemo0526** [comment]
Ok, Thank for your replying!

**Comment by nemo0526** [comment]
Hello, may I ask that have you ever use one 2080ti for the training before? My GPU is one 2080ti, it seems that the model is out of memory. If not, is there any solution to decrease the model size except for batch size and torch.no_grad()? Thanks!

![gpu](https://user-images.githubusercontent.com/63770299/198686703-03685c0f-6de8-4672-b431-fccaffbccdb5.png)
