### ISSUE TITLE
Paper question

### ISSUE THREAD

**Issue by nemo0526** [hbchen121/AICITY2022_Track2_SSM#2]
Hello, may I ask that what is the meaning of W1&W2 in the formula in paper chapter 3.3.1 ?
![formula](https://user-images.githubusercontent.com/63770299/197327162-ed0f6327-d89f-4669-8c11-881d93e9d3f2.png)

**Comment by hbchen121** [comment]
You can understand that it's a nonlinear mapping using the BatchNorm/LayerNorm, and code like: https://github.com/hbchen121/AICITY2022_Track2_SSM/blob/master/models/siamese_baseline_v2.py#L145

**Comment by nemo0526** [comment]
Okay,thank you! In the other hand, I have some problem when generating the iou motion map. It seems working successfully in the beginnig, but after few minutes it just stop generating. Have you met the problem before?
![iou generate](https://user-images.githubusercontent.com/63770299/197387309-2d50f75e-9ccf-49df-98c4-a0732d214cff.png)

**Comment by ZhaoChuyang** [comment]
Did you use multiprocessing in your code? Sometimes it may hang because of the multiprocessing issue. You can try modifying the script to run in single process.

**Comment by nemo0526** [comment]
Thanks! It works for me to change num_work to 1.
