### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by nemo0526** [hbchen121/AICITY2022_Track2_SSM#3]
I got a TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.Image.Image'> when running bash run/single_baseline_aug1.sh. The problem seems to be solve by transform to tensor in the internet, have you met this problem?

![transform](https://user-images.githubusercontent.com/63770299/198694776-becd8314-9a35-47de-a4d5-61032f0a3fce.png)

**Comment by hbchen121** [comment]
It seems that you loaded an Image object of type PIL , but Pytorch expects a torch tensor.

You can check if PIL.Image is converted to tensor in image augmentation, like ToTensor

**Comment by nemo0526** [comment]
May I ask that which file you change the datatype?

**Comment by hbchen121** [comment]
The dataloader of pytorch load data by `dataset.__getitem__()`, so you can see the `__getitem__` function in: https://github.com/hbchen121/AICITY2022_Track2_SSM/blob/a827e0cebb89e728654f00357c0301852af3d121/datasets.py

**Comment by nemo0526** [comment]
I tried to change the datatype of tmp_index,flag and track in __getitem__ ,but it can't be changed to tensor due to the error below.
The other solution  says that I can modify "transform=transform_train" to "transform=transform" by setting a transform method, but it doesn't work out. I guess that maybe my data augmentation was not doing well?

![PIL](https://user-images.githubusercontent.com/63770299/200360972-8e3a0235-2d3f-4693-80da-de1a6b3cde5a.png)

**Comment by hbchen121** [comment]
The pytorch dataloader is parallel (i.e., multiple workers), you can run `dataset.__getitem__()` directly after building a dataset.
And then debug the data load in `__getitem__`. Maybe IPython is a good tool to help you debug. such as `IPython.embed()`

**Comment by nemo0526** [comment]
Okay, thanks a lot! Finally solved it.
