### ISSUE TITLE
single_baseline_aug1.pth

### ISSUE THREAD

**Issue by nemo0526** [hbchen121/AICITY2022_Track2_SSM#4]
Hello, I can't see single_baseline_aug1.pth file in the google cloud you gave.

**Comment by hbchen121** [comment]
We did forget to upload it. However, this file does not affect the reproduction process, you can use the remaining checkpoints for model ensemble.

**Comment by nemo0526** [comment]
Okay, I'll try it. Thanks for replying! I have a question that what the difference between single_baseline_aug1.sh and single_baseline_aug1_plus.sh?

**Comment by hbchen121** [comment]
Their learning rate decay are different, plus is better in test/valid set.
